/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as CompanyNewRouteImport } from './routes/company/new'
import { Route as DevApiSandboxRouteImport } from './routes/dev/api-sandbox'
import { Route as DevTestApiRouteImport } from './routes/dev/test-api'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as TransactionsVouchersRouteImport } from './routes/transactions/vouchers'
import { Route as AccountsMastersLedgerIndexRouteImport } from './routes/accounts/masters/ledger/index'
import { Route as AccountsMastersLedgerNewRouteImport } from './routes/accounts/masters/ledger/new'
import { Route as InventoryTransactionsVoucherTypeIndexRouteImport } from './routes/inventory/transactions/voucher-type/index'
import { Route as InventoryMastersStockItemNewIndexRouteImport } from './routes/inventory/masters/stock-item/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNewRoute = CompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DevApiSandboxRoute = DevApiSandboxRouteImport.update({
  id: '/dev/api-sandbox',
  path: '/dev/api-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DevTestApiRoute = DevTestApiRouteImport.update({
  id: '/dev/test-api',
  path: '/dev/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsVouchersRoute = TransactionsVouchersRouteImport.update({
  id: '/transactions/vouchers',
  path: '/transactions/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsMastersLedgerIndexRoute =
  AccountsMastersLedgerIndexRouteImport.update({
    id: '/accounts/masters/ledger/',
    path: '/accounts/masters/ledger/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsMastersLedgerNewRoute =
  AccountsMastersLedgerNewRouteImport.update({
    id: '/accounts/masters/ledger/new',
    path: '/accounts/masters/ledger/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryTransactionsVoucherTypeIndexRoute =
  InventoryTransactionsVoucherTypeIndexRouteImport.update({
    id: '/inventory/transactions/voucher-type/',
    path: '/inventory/transactions/voucher-type/',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryMastersStockItemNewIndexRoute =
  InventoryMastersStockItemNewIndexRouteImport.update({
    id: '/inventory/masters/stock-item/new/',
    path: '/inventory/masters/stock-item/new/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/masters': typeof MastersRoute
  '/company/new': typeof CompanyNewRoute
  '/dev/api-sandbox': typeof DevApiSandboxRoute
  '/dev/test-api': typeof DevTestApiRoute
  '/transactions/vouchers': typeof TransactionsVouchersRoute
  '/signup/': typeof SignupIndexRoute
  '/accounts/masters/ledger/new': typeof AccountsMastersLedgerNewRoute
  '/accounts/masters/ledger/': typeof AccountsMastersLedgerIndexRoute
  '/inventory/transactions/voucher-type/': typeof InventoryTransactionsVoucherTypeIndexRoute
  '/inventory/masters/stock-item/new/': typeof InventoryMastersStockItemNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/masters': typeof MastersRoute
  '/company/new': typeof CompanyNewRoute
  '/dev/api-sandbox': typeof DevApiSandboxRoute
  '/dev/test-api': typeof DevTestApiRoute
  '/transactions/vouchers': typeof TransactionsVouchersRoute
  '/signup': typeof SignupIndexRoute
  '/accounts/masters/ledger/new': typeof AccountsMastersLedgerNewRoute
  '/accounts/masters/ledger': typeof AccountsMastersLedgerIndexRoute
  '/inventory/transactions/voucher-type': typeof InventoryTransactionsVoucherTypeIndexRoute
  '/inventory/masters/stock-item/new': typeof InventoryMastersStockItemNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/masters': typeof MastersRoute
  '/company/new': typeof CompanyNewRoute
  '/dev/api-sandbox': typeof DevApiSandboxRoute
  '/dev/test-api': typeof DevTestApiRoute
  '/transactions/vouchers': typeof TransactionsVouchersRoute
  '/signup/': typeof SignupIndexRoute
  '/accounts/masters/ledger/new': typeof AccountsMastersLedgerNewRoute
  '/accounts/masters/ledger/': typeof AccountsMastersLedgerIndexRoute
  '/inventory/transactions/voucher-type/': typeof InventoryTransactionsVoucherTypeIndexRoute
  '/inventory/masters/stock-item/new/': typeof InventoryMastersStockItemNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/masters'
    | '/company/new'
    | '/dev/api-sandbox'
    | '/dev/test-api'
    | '/transactions/vouchers'
    | '/signup/'
    | '/accounts/masters/ledger/new'
    | '/accounts/masters/ledger/'
    | '/inventory/transactions/voucher-type/'
    | '/inventory/masters/stock-item/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/masters'
    | '/company/new'
    | '/dev/api-sandbox'
    | '/dev/test-api'
    | '/transactions/vouchers'
    | '/signup'
    | '/accounts/masters/ledger/new'
    | '/accounts/masters/ledger'
    | '/inventory/transactions/voucher-type'
    | '/inventory/masters/stock-item/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/masters'
    | '/company/new'
    | '/dev/api-sandbox'
    | '/dev/test-api'
    | '/transactions/vouchers'
    | '/signup/'
    | '/accounts/masters/ledger/new'
    | '/accounts/masters/ledger/'
    | '/inventory/transactions/voucher-type/'
    | '/inventory/masters/stock-item/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MastersRoute: typeof MastersRoute
  CompanyNewRoute: typeof CompanyNewRoute
  DevApiSandboxRoute: typeof DevApiSandboxRoute
  DevTestApiRoute: typeof DevTestApiRoute
  TransactionsVouchersRoute: typeof TransactionsVouchersRoute
  SignupIndexRoute: typeof SignupIndexRoute
  AccountsMastersLedgerNewRoute: typeof AccountsMastersLedgerNewRoute
  AccountsMastersLedgerIndexRoute: typeof AccountsMastersLedgerIndexRoute
  InventoryTransactionsVoucherTypeIndexRoute: typeof InventoryTransactionsVoucherTypeIndexRoute
  InventoryMastersStockItemNewIndexRoute: typeof InventoryMastersStockItemNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/new': {
      id: '/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof CompanyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/api-sandbox': {
      id: '/dev/api-sandbox'
      path: '/dev/api-sandbox'
      fullPath: '/dev/api-sandbox'
      preLoaderRoute: typeof DevApiSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/test-api': {
      id: '/dev/test-api'
      path: '/dev/test-api'
      fullPath: '/dev/test-api'
      preLoaderRoute: typeof DevTestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/vouchers': {
      id: '/transactions/vouchers'
      path: '/transactions/vouchers'
      fullPath: '/transactions/vouchers'
      preLoaderRoute: typeof TransactionsVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/masters/ledger/': {
      id: '/accounts/masters/ledger/'
      path: '/accounts/masters/ledger'
      fullPath: '/accounts/masters/ledger/'
      preLoaderRoute: typeof AccountsMastersLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/masters/ledger/new': {
      id: '/accounts/masters/ledger/new'
      path: '/accounts/masters/ledger/new'
      fullPath: '/accounts/masters/ledger/new'
      preLoaderRoute: typeof AccountsMastersLedgerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/transactions/voucher-type/': {
      id: '/inventory/transactions/voucher-type/'
      path: '/inventory/transactions/voucher-type'
      fullPath: '/inventory/transactions/voucher-type/'
      preLoaderRoute: typeof InventoryTransactionsVoucherTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/masters/stock-item/new/': {
      id: '/inventory/masters/stock-item/new/'
      path: '/inventory/masters/stock-item/new'
      fullPath: '/inventory/masters/stock-item/new/'
      preLoaderRoute: typeof InventoryMastersStockItemNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MastersRoute: MastersRoute,
  CompanyNewRoute: CompanyNewRoute,
  DevApiSandboxRoute: DevApiSandboxRoute,
  DevTestApiRoute: DevTestApiRoute,
  TransactionsVouchersRoute: TransactionsVouchersRoute,
  SignupIndexRoute: SignupIndexRoute,
  AccountsMastersLedgerNewRoute: AccountsMastersLedgerNewRoute,
  AccountsMastersLedgerIndexRoute: AccountsMastersLedgerIndexRoute,
  InventoryTransactionsVoucherTypeIndexRoute:
    InventoryTransactionsVoucherTypeIndexRoute,
  InventoryMastersStockItemNewIndexRoute:
    InventoryMastersStockItemNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
