/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TestApiRouteImport } from './routes/test-api'
import { Route as CompanyNewRouteImport } from './routes/company/new'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as AccountsMastersLedgerIndexRouteImport } from './routes/accounts/masters/ledger/index'
import { Route as AccountsMastersLedgerNewRouteImport } from './routes/accounts/masters/ledger/new'
import { Route as AccountsMastersVoucherTypeIndexRouteImport } from './routes/accounts/masters/voucher-type/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TestApiRoute = TestApiRouteImport.update({
  id: '/test-api',
  path: '/test-api',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyNewRoute = CompanyNewRouteImport.update({
  id: '/company/new',
  path: '/company/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsMastersLedgerIndexRoute =
  AccountsMastersLedgerIndexRouteImport.update({
    id: '/accounts/masters/ledger/',
    path: '/accounts/masters/ledger/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsMastersLedgerNewRoute =
  AccountsMastersLedgerNewRouteImport.update({
    id: '/accounts/masters/ledger/new',
    path: '/accounts/masters/ledger/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsMastersVoucherTypeIndexRoute =
  AccountsMastersVoucherTypeIndexRouteImport.update({
    id: '/accounts/masters/voucher-type/',
    path: '/accounts/masters/voucher-type/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/test-api': typeof TestApiRoute
  '/company/new': typeof CompanyNewRoute
  '/signup/': typeof SignupIndexRoute
  '/accounts/masters/ledger/new': typeof AccountsMastersLedgerNewRoute
  '/accounts/masters/ledger/': typeof AccountsMastersLedgerIndexRoute
  '/accounts/masters/voucher-type/': typeof AccountsMastersVoucherTypeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/test-api': typeof TestApiRoute
  '/company/new': typeof CompanyNewRoute
  '/signup': typeof SignupIndexRoute
  '/accounts/masters/ledger/new': typeof AccountsMastersLedgerNewRoute
  '/accounts/masters/ledger': typeof AccountsMastersLedgerIndexRoute
  '/accounts/masters/voucher-type': typeof AccountsMastersVoucherTypeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/test-api': typeof TestApiRoute
  '/company/new': typeof CompanyNewRoute
  '/signup/': typeof SignupIndexRoute
  '/accounts/masters/ledger/new': typeof AccountsMastersLedgerNewRoute
  '/accounts/masters/ledger/': typeof AccountsMastersLedgerIndexRoute
  '/accounts/masters/voucher-type/': typeof AccountsMastersVoucherTypeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/test-api'
    | '/company/new'
    | '/signup/'
    | '/accounts/masters/ledger/new'
    | '/accounts/masters/ledger/'
    | '/accounts/masters/voucher-type/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/test-api'
    | '/company/new'
    | '/signup'
    | '/accounts/masters/ledger/new'
    | '/accounts/masters/ledger'
    | '/accounts/masters/voucher-type'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/test-api'
    | '/company/new'
    | '/signup/'
    | '/accounts/masters/ledger/new'
    | '/accounts/masters/ledger/'
    | '/accounts/masters/voucher-type/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TestApiRoute: typeof TestApiRoute
  CompanyNewRoute: typeof CompanyNewRoute
  SignupIndexRoute: typeof SignupIndexRoute
  AccountsMastersLedgerNewRoute: typeof AccountsMastersLedgerNewRoute
  AccountsMastersLedgerIndexRoute: typeof AccountsMastersLedgerIndexRoute
  AccountsMastersVoucherTypeIndexRoute: typeof AccountsMastersVoucherTypeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-api': {
      id: '/test-api'
      path: '/test-api'
      fullPath: '/test-api'
      preLoaderRoute: typeof TestApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/new': {
      id: '/company/new'
      path: '/company/new'
      fullPath: '/company/new'
      preLoaderRoute: typeof CompanyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/masters/ledger/': {
      id: '/accounts/masters/ledger/'
      path: '/accounts/masters/ledger'
      fullPath: '/accounts/masters/ledger/'
      preLoaderRoute: typeof AccountsMastersLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/masters/ledger/new': {
      id: '/accounts/masters/ledger/new'
      path: '/accounts/masters/ledger/new'
      fullPath: '/accounts/masters/ledger/new'
      preLoaderRoute: typeof AccountsMastersLedgerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/masters/voucher-type/': {
      id: '/accounts/masters/voucher-type/'
      path: '/accounts/masters/voucher-type'
      fullPath: '/accounts/masters/voucher-type/'
      preLoaderRoute: typeof AccountsMastersVoucherTypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TestApiRoute: TestApiRoute,
  CompanyNewRoute: CompanyNewRoute,
  SignupIndexRoute: SignupIndexRoute,
  AccountsMastersLedgerNewRoute: AccountsMastersLedgerNewRoute,
  AccountsMastersLedgerIndexRoute: AccountsMastersLedgerIndexRoute,
  AccountsMastersVoucherTypeIndexRoute: AccountsMastersVoucherTypeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
